export const runtime = "nodejs";
export const dynamic = "force-dynamic";

import { NextResponse } from "next/server";
import { Resend } from "resend";
import crypto from "crypto";
import chromium from "@sparticuz/chromium";
import puppeteer from "puppeteer-core";

// Resend
const resendKey = process.env.RESEND_API_KEY!;
const resend = new Resend(resendKey);

// Where the PDF goes
const FORMS_TO = "owner@mypetai.app";

/**
 * Very small HTML-escape helper so user input can't break the PDF HTML.
 */
function esc(input: unknown) {
  return String(input ?? "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

/**
 * Render a printable HTML version of the form (filled with user values).
 * This should match the layout you render on the page, but without inputs.
 * Keep it simple: table/grid + your values.
 */
function renderGordonPdfHtml(form: Record<string, any>) {
  const box = (checked: boolean) =>
    `<span class="box ${checked ? "checked" : ""}">${checked ? "✓" : ""}</span>`;

  return `<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <style>
    @page { size: A4; margin: 12mm; }
    body { font-family: Arial, Helvetica, sans-serif; color:#000; }
    .header { border-bottom: 3px solid #000; padding-bottom: 8px; margin-bottom: 10px; }
    h1 { font-size: 16px; margin: 0; }
    .small { font-size: 10px; line-height: 1.35; }
    .grid2 { display:grid; grid-template-columns: 1fr 1fr; gap: 8px; }
    .field { font-size: 12px; }
    .label { font-weight: 700; font-size: 12px; margin-bottom: 2px; }
    .value { border: 1px solid #000; padding: 6px 8px; min-height: 18px; }
    .section { margin-top: 10px; border-top: 2px solid #000; padding-top: 8px; }
    .box { display:inline-flex; width:14px; height:14px; border:1px solid #000; align-items:center; justify-content:center; font-size:12px; line-height:1; }
    .checked { background:#000; color:#fff; }
    table { width:100%; border-collapse: collapse; margin-top: 8px; font-size: 12px; }
    td { border: 1px solid #000; padding: 6px; vertical-align: top; }
    .right { width: 180px; }
  </style>
</head>
<body>
  <div class="header">
    <h1>Skills & Jobs Centre Registration</h1>
    <div class="small">Generated by MyPetAI+. Please verify details.</div>
  </div>

  <div class="grid2">
    <div class="field">
      <div class="label">First Name</div>
      <div class="value">${esc(form.firstName)}</div>
    </div>
    <div class="field">
      <div class="label">Surname</div>
      <div class="value">${esc(form.surname)}</div>
    </div>

    <div class="field" style="grid-column:1/-1">
      <div class="label">Email</div>
      <div class="value">${esc(form.email)}</div>
    </div>

    <div class="field">
      <div class="label">Mobile</div>
      <div class="value">${esc(form.mobile)}</div>
    </div>
    <div class="field">
      <div class="label">Home phone</div>
      <div class="value">${esc(form.homePhone)}</div>
    </div>

    <div class="field">
      <div class="label">City/Suburb</div>
      <div class="value">${esc(form.citySuburb)}</div>
    </div>
    <div class="field">
      <div class="label">State / Post code</div>
      <div class="value">${esc(form.state)}${form.postCode ? " / " + esc(form.postCode) : ""}</div>
    </div>

    <div class="field">
      <div class="label">D.O.B.</div>
      <div class="value">${esc(form.dob)}</div>
    </div>
  </div>

  <div class="section">
    <div class="label">Gender</div>
    <div class="small">
      ${box(form.gender === "Female")} Female&nbsp;&nbsp;
      ${box(form.gender === "Male")} Male&nbsp;&nbsp;
      ${box(form.gender === "Other")} Other ${form.gender === "Other" ? "— " + esc(form.genderOtherText) : ""}
    </div>
  </div>

  <table>
    <tr>
      <td>Q1: Apprenticeship?</td>
      <td class="right">${box(form.q1 === "Yes")} Yes &nbsp;&nbsp; ${box(form.q1 === "No")} No</td>
    </tr>
    <tr>
      <td>Q2: Traineeship?</td>
      <td class="right">${box(form.q2 === "Yes")} Yes &nbsp;&nbsp; ${box(form.q2 === "No")} No</td>
    </tr>
    <tr>
      <td>Q3: Currently employed?</td>
      <td class="right">${box(form.q3 === "Employed")} Employed &nbsp;&nbsp; ${box(form.q3 === "Unemployed")} Unemployed</td>
    </tr>
    <tr>
      <td>Q4: Underemployed?</td>
      <td class="right">${box(form.q4 === "Yes")} Yes &nbsp;&nbsp; ${box(form.q4 === "No")} No</td>
    </tr>
    <tr>
      <td>Q5: Currently studying?</td>
      <td class="right">${box(form.q5 === "Yes")} Yes &nbsp;&nbsp; ${box(form.q5 === "No")} No</td>
    </tr>
    <tr>
      <td>Q6: Carer or Parent?</td>
      <td class="right">${box(form.q6 === "Yes")} Yes &nbsp;&nbsp; ${box(form.q6 === "No")} No</td>
    </tr>
    <tr>
      <td>Q7: Retrenched last 5 years?</td>
      <td class="right">${box(form.q7 === "Yes")} Yes &nbsp;&nbsp; ${box(form.q7 === "No")} No</td>
    </tr>
    <tr>
      <td>Q8: Disability/impairment/long-term condition?</td>
      <td class="right">${box(form.q8 === "Yes")} Yes &nbsp;&nbsp; ${box(form.q8 === "No")} No</td>
    </tr>
  </table>

  <div class="section">
    <div class="label">How did you FIRST hear about The Gordon Skills and Jobs Centre?</div>
    <div class="value" style="margin-top:6px">
      ${esc(form.hearAbout)}${String(form.hearAbout || "").includes("Other") ? " — " + esc(form.hearOtherText) : ""}
    </div>
  </div>

  <div class="section small">
    ${box(!!form.optOutEmails)} I do not wish to be contacted regarding job opportunities, workshops, information sessions or training opportunities.
  </div>
</body>
</html>`;
}

/**
 * HTML -> PDF buffer using headless chromium (works on Vercel node runtime)
 */
async function htmlToPdfBuffer1(html: string): Promise<Buffer> {
  const executablePath = await chromium.executablePath();

const browser = await puppeteer.launch({
  args: chromium.args,
  executablePath,
  headless: true, // always safe
});

  try {
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: "networkidle0" });

    const pdf = await page.pdf({
      format: "A4",
      printBackground: true,
      preferCSSPageSize: true,
    });

    return Buffer.from(pdf);
  } finally {
    await browser.close();
  }
}

async function htmlToPdfBuffer(html: string): Promise<Buffer> {
  const executablePath = await chromium.executablePath();

  const browser = await puppeteer.launch({
    args: chromium.args,
    executablePath,
    headless: true,
  });

  try {
    const page = await browser.newPage();
    await page.setViewport({ width: 1240, height: 1754 });
    await page.setContent(html, { waitUntil: "networkidle0" });

    const pdf = await page.pdf({
      format: "A4",
      printBackground: true,
      preferCSSPageSize: true,
    });

    return Buffer.from(pdf);
  } finally {
    await browser.close();
  }
}

export async function POST(req: Request) {
  try {
    const { form, petname } = await req.json();

    // Honeypot (copy your pattern)
    if (petname && String(petname).trim().length > 0) {
      return NextResponse.json({ success: true });
    }

    // Minimal validation (adjust as needed)
    if (!form?.email || !String(form.email).includes("@")) {
      return NextResponse.json(
        { success: false, error: "Invalid payload" },
        { status: 400 }
      );
    }

    // 1) build HTML for PDF
    const pdfHtml = renderGordonPdfHtml(form);

    // 2) generate PDF buffer
    const pdfBuffer = await htmlToPdfBuffer(pdfHtml);

    // 3) send email with attachment via Resend
    const safeName = (form.firstName || "").toString().trim() || "Unknown";
    const safeEmail = (form.email || "").toString().trim() || "Unknown";

    const submissionId = crypto.randomBytes(8).toString("hex");
    const filename = `gordon-registration-${submissionId}.pdf`;

    await resend.emails.send({
      from: "MyPetAI+ <hello@mypetai.app>",
      to: FORMS_TO,
      replyTo: safeEmail,
      subject: `📄 Gordon Form Submission — ${safeName}`,
      text: [
        "New Gordon form submission",
        "",
        `Name: ${safeName} ${String(form.surname || "").trim()}`,
        `Email: ${safeEmail}`,
        `Submission ID: ${submissionId}`,
        "",
        "PDF attached.",
      ].join("\n"),
      html: `
        <div style="font-family:Poppins,sans-serif;line-height:1.6;color:#333;">
          <h2>New Gordon form submission</h2>
          <p><strong>Name:</strong> ${esc(safeName)} ${esc(form.surname)}</p>
          <p><strong>Email:</strong> ${esc(safeEmail)}</p>
          <p><strong>Submission ID:</strong> ${esc(submissionId)}</p>
          <p>PDF is attached.</p>
        </div>
      `,
      attachments: [
        {
          filename,
          content: pdfBuffer.toString("base64"),
        },
      ],
    });

    return NextResponse.json({ success: true });
  } catch (err) {
    console.error("❌ Error in /api/forms/gordon:", err);
    return NextResponse.json(
      { success: false, error: "Internal Server Error" },
      { status: 500 }
    );
  }
}